/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TerminosRouteImport } from './routes/terminos'
import { Route as SobreNosotrosRouteImport } from './routes/sobre-nosotros'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SelectorRouteImport } from './routes/selector'
import { Route as PrivacidadRouteImport } from './routes/privacidad'
import { Route as MetodologiaRouteImport } from './routes/metodologia'
import { Route as MejoresHumidificadoresRouteImport } from './routes/mejores-humidificadores'
import { Route as GuiaDeCompraRouteImport } from './routes/guia-de-compra'
import { Route as EnRouteImport } from './routes/en'
import { Route as CosteDeUsoRouteImport } from './routes/coste-de-uso'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as CalculadoraRouteImport } from './routes/calculadora'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AvisoAfiliacionRouteImport } from './routes/aviso-afiliacion'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EnIndexRouteImport } from './routes/en.index'
import { Route as ProductoSlugRouteImport } from './routes/producto.$slug'
import { Route as EnRunningCostRouteImport } from './routes/en.running-cost'
import { Route as EnCalculatorRouteImport } from './routes/en.calculator'
import { Route as CategoriaSlugRouteImport } from './routes/categoria.$slug'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'

const TerminosRoute = TerminosRouteImport.update({
  id: '/terminos',
  path: '/terminos',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreNosotrosRoute = SobreNosotrosRouteImport.update({
  id: '/sobre-nosotros',
  path: '/sobre-nosotros',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SelectorRoute = SelectorRouteImport.update({
  id: '/selector',
  path: '/selector',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadRoute = PrivacidadRouteImport.update({
  id: '/privacidad',
  path: '/privacidad',
  getParentRoute: () => rootRouteImport,
} as any)
const MetodologiaRoute = MetodologiaRouteImport.update({
  id: '/metodologia',
  path: '/metodologia',
  getParentRoute: () => rootRouteImport,
} as any)
const MejoresHumidificadoresRoute = MejoresHumidificadoresRouteImport.update({
  id: '/mejores-humidificadores',
  path: '/mejores-humidificadores',
  getParentRoute: () => rootRouteImport,
} as any)
const GuiaDeCompraRoute = GuiaDeCompraRouteImport.update({
  id: '/guia-de-compra',
  path: '/guia-de-compra',
  getParentRoute: () => rootRouteImport,
} as any)
const EnRoute = EnRouteImport.update({
  id: '/en',
  path: '/en',
  getParentRoute: () => rootRouteImport,
} as any)
const CosteDeUsoRoute = CosteDeUsoRouteImport.update({
  id: '/coste-de-uso',
  path: '/coste-de-uso',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculadoraRoute = CalculadoraRouteImport.update({
  id: '/calculadora',
  path: '/calculadora',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AvisoAfiliacionRoute = AvisoAfiliacionRouteImport.update({
  id: '/aviso-afiliacion',
  path: '/aviso-afiliacion',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EnIndexRoute = EnIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EnRoute,
} as any)
const ProductoSlugRoute = ProductoSlugRouteImport.update({
  id: '/producto/$slug',
  path: '/producto/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const EnRunningCostRoute = EnRunningCostRouteImport.update({
  id: '/running-cost',
  path: '/running-cost',
  getParentRoute: () => EnRoute,
} as any)
const EnCalculatorRoute = EnCalculatorRouteImport.update({
  id: '/calculator',
  path: '/calculator',
  getParentRoute: () => EnRoute,
} as any)
const CategoriaSlugRoute = CategoriaSlugRouteImport.update({
  id: '/categoria/$slug',
  path: '/categoria/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aviso-afiliacion': typeof AvisoAfiliacionRoute
  '/blog': typeof BlogRouteWithChildren
  '/calculadora': typeof CalculadoraRoute
  '/cookies': typeof CookiesRoute
  '/coste-de-uso': typeof CosteDeUsoRoute
  '/en': typeof EnRouteWithChildren
  '/guia-de-compra': typeof GuiaDeCompraRoute
  '/mejores-humidificadores': typeof MejoresHumidificadoresRoute
  '/metodologia': typeof MetodologiaRoute
  '/privacidad': typeof PrivacidadRoute
  '/selector': typeof SelectorRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre-nosotros': typeof SobreNosotrosRoute
  '/terminos': typeof TerminosRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/categoria/$slug': typeof CategoriaSlugRoute
  '/en/calculator': typeof EnCalculatorRoute
  '/en/running-cost': typeof EnRunningCostRoute
  '/producto/$slug': typeof ProductoSlugRoute
  '/en/': typeof EnIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aviso-afiliacion': typeof AvisoAfiliacionRoute
  '/blog': typeof BlogRouteWithChildren
  '/calculadora': typeof CalculadoraRoute
  '/cookies': typeof CookiesRoute
  '/coste-de-uso': typeof CosteDeUsoRoute
  '/guia-de-compra': typeof GuiaDeCompraRoute
  '/mejores-humidificadores': typeof MejoresHumidificadoresRoute
  '/metodologia': typeof MetodologiaRoute
  '/privacidad': typeof PrivacidadRoute
  '/selector': typeof SelectorRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre-nosotros': typeof SobreNosotrosRoute
  '/terminos': typeof TerminosRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/categoria/$slug': typeof CategoriaSlugRoute
  '/en/calculator': typeof EnCalculatorRoute
  '/en/running-cost': typeof EnRunningCostRoute
  '/producto/$slug': typeof ProductoSlugRoute
  '/en': typeof EnIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/aviso-afiliacion': typeof AvisoAfiliacionRoute
  '/blog': typeof BlogRouteWithChildren
  '/calculadora': typeof CalculadoraRoute
  '/cookies': typeof CookiesRoute
  '/coste-de-uso': typeof CosteDeUsoRoute
  '/en': typeof EnRouteWithChildren
  '/guia-de-compra': typeof GuiaDeCompraRoute
  '/mejores-humidificadores': typeof MejoresHumidificadoresRoute
  '/metodologia': typeof MetodologiaRoute
  '/privacidad': typeof PrivacidadRoute
  '/selector': typeof SelectorRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre-nosotros': typeof SobreNosotrosRoute
  '/terminos': typeof TerminosRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/categoria/$slug': typeof CategoriaSlugRoute
  '/en/calculator': typeof EnCalculatorRoute
  '/en/running-cost': typeof EnRunningCostRoute
  '/producto/$slug': typeof ProductoSlugRoute
  '/en/': typeof EnIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aviso-afiliacion'
    | '/blog'
    | '/calculadora'
    | '/cookies'
    | '/coste-de-uso'
    | '/en'
    | '/guia-de-compra'
    | '/mejores-humidificadores'
    | '/metodologia'
    | '/privacidad'
    | '/selector'
    | '/sitemap.xml'
    | '/sobre-nosotros'
    | '/terminos'
    | '/blog/$slug'
    | '/categoria/$slug'
    | '/en/calculator'
    | '/en/running-cost'
    | '/producto/$slug'
    | '/en/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aviso-afiliacion'
    | '/blog'
    | '/calculadora'
    | '/cookies'
    | '/coste-de-uso'
    | '/guia-de-compra'
    | '/mejores-humidificadores'
    | '/metodologia'
    | '/privacidad'
    | '/selector'
    | '/sitemap.xml'
    | '/sobre-nosotros'
    | '/terminos'
    | '/blog/$slug'
    | '/categoria/$slug'
    | '/en/calculator'
    | '/en/running-cost'
    | '/producto/$slug'
    | '/en'
  id:
    | '__root__'
    | '/'
    | '/aviso-afiliacion'
    | '/blog'
    | '/calculadora'
    | '/cookies'
    | '/coste-de-uso'
    | '/en'
    | '/guia-de-compra'
    | '/mejores-humidificadores'
    | '/metodologia'
    | '/privacidad'
    | '/selector'
    | '/sitemap.xml'
    | '/sobre-nosotros'
    | '/terminos'
    | '/blog/$slug'
    | '/categoria/$slug'
    | '/en/calculator'
    | '/en/running-cost'
    | '/producto/$slug'
    | '/en/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AvisoAfiliacionRoute: typeof AvisoAfiliacionRoute
  BlogRoute: typeof BlogRouteWithChildren
  CalculadoraRoute: typeof CalculadoraRoute
  CookiesRoute: typeof CookiesRoute
  CosteDeUsoRoute: typeof CosteDeUsoRoute
  EnRoute: typeof EnRouteWithChildren
  GuiaDeCompraRoute: typeof GuiaDeCompraRoute
  MejoresHumidificadoresRoute: typeof MejoresHumidificadoresRoute
  MetodologiaRoute: typeof MetodologiaRoute
  PrivacidadRoute: typeof PrivacidadRoute
  SelectorRoute: typeof SelectorRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SobreNosotrosRoute: typeof SobreNosotrosRoute
  TerminosRoute: typeof TerminosRoute
  CategoriaSlugRoute: typeof CategoriaSlugRoute
  ProductoSlugRoute: typeof ProductoSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terminos': {
      id: '/terminos'
      path: '/terminos'
      fullPath: '/terminos'
      preLoaderRoute: typeof TerminosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre-nosotros': {
      id: '/sobre-nosotros'
      path: '/sobre-nosotros'
      fullPath: '/sobre-nosotros'
      preLoaderRoute: typeof SobreNosotrosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/selector': {
      id: '/selector'
      path: '/selector'
      fullPath: '/selector'
      preLoaderRoute: typeof SelectorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidad': {
      id: '/privacidad'
      path: '/privacidad'
      fullPath: '/privacidad'
      preLoaderRoute: typeof PrivacidadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metodologia': {
      id: '/metodologia'
      path: '/metodologia'
      fullPath: '/metodologia'
      preLoaderRoute: typeof MetodologiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mejores-humidificadores': {
      id: '/mejores-humidificadores'
      path: '/mejores-humidificadores'
      fullPath: '/mejores-humidificadores'
      preLoaderRoute: typeof MejoresHumidificadoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guia-de-compra': {
      id: '/guia-de-compra'
      path: '/guia-de-compra'
      fullPath: '/guia-de-compra'
      preLoaderRoute: typeof GuiaDeCompraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en': {
      id: '/en'
      path: '/en'
      fullPath: '/en'
      preLoaderRoute: typeof EnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coste-de-uso': {
      id: '/coste-de-uso'
      path: '/coste-de-uso'
      fullPath: '/coste-de-uso'
      preLoaderRoute: typeof CosteDeUsoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculadora': {
      id: '/calculadora'
      path: '/calculadora'
      fullPath: '/calculadora'
      preLoaderRoute: typeof CalculadoraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aviso-afiliacion': {
      id: '/aviso-afiliacion'
      path: '/aviso-afiliacion'
      fullPath: '/aviso-afiliacion'
      preLoaderRoute: typeof AvisoAfiliacionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/': {
      id: '/en/'
      path: '/'
      fullPath: '/en/'
      preLoaderRoute: typeof EnIndexRouteImport
      parentRoute: typeof EnRoute
    }
    '/producto/$slug': {
      id: '/producto/$slug'
      path: '/producto/$slug'
      fullPath: '/producto/$slug'
      preLoaderRoute: typeof ProductoSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/running-cost': {
      id: '/en/running-cost'
      path: '/running-cost'
      fullPath: '/en/running-cost'
      preLoaderRoute: typeof EnRunningCostRouteImport
      parentRoute: typeof EnRoute
    }
    '/en/calculator': {
      id: '/en/calculator'
      path: '/calculator'
      fullPath: '/en/calculator'
      preLoaderRoute: typeof EnCalculatorRouteImport
      parentRoute: typeof EnRoute
    }
    '/categoria/$slug': {
      id: '/categoria/$slug'
      path: '/categoria/$slug'
      fullPath: '/categoria/$slug'
      preLoaderRoute: typeof CategoriaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
  }
}

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface EnRouteChildren {
  EnCalculatorRoute: typeof EnCalculatorRoute
  EnRunningCostRoute: typeof EnRunningCostRoute
  EnIndexRoute: typeof EnIndexRoute
}

const EnRouteChildren: EnRouteChildren = {
  EnCalculatorRoute: EnCalculatorRoute,
  EnRunningCostRoute: EnRunningCostRoute,
  EnIndexRoute: EnIndexRoute,
}

const EnRouteWithChildren = EnRoute._addFileChildren(EnRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AvisoAfiliacionRoute: AvisoAfiliacionRoute,
  BlogRoute: BlogRouteWithChildren,
  CalculadoraRoute: CalculadoraRoute,
  CookiesRoute: CookiesRoute,
  CosteDeUsoRoute: CosteDeUsoRoute,
  EnRoute: EnRouteWithChildren,
  GuiaDeCompraRoute: GuiaDeCompraRoute,
  MejoresHumidificadoresRoute: MejoresHumidificadoresRoute,
  MetodologiaRoute: MetodologiaRoute,
  PrivacidadRoute: PrivacidadRoute,
  SelectorRoute: SelectorRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SobreNosotrosRoute: SobreNosotrosRoute,
  TerminosRoute: TerminosRoute,
  CategoriaSlugRoute: CategoriaSlugRoute,
  ProductoSlugRoute: ProductoSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
